/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-10-13 08:13:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class LabReportDelete_jsp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1728787558180L));
    _jspx_dependants.put("jar:file:/D:/2%20nd%20Year/OOP/final%20echanneling/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PatientDemo/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/LabReportDelete.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/Home.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(" .navbar {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("            background: rgb(255, 255, 255);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 0 50px;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            z-index: 100;\r\n");
      out.write("            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("         .logo {\r\n");
      out.write("            color: #000000;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links li {\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links li a {\r\n");
      out.write("            color: #000000;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hover effect for links */\r\n");
      out.write("        .nav-links li a:hover {\r\n");
      out.write("            color: cadetblue;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Log Out button */\r\n");
      out.write("        .auth-buttons .btn {\r\n");
      out.write("            background-color: transparent;\r\n");
      out.write("            color: #000;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-buttons .btn:hover {\r\n");
      out.write("            color: cadetblue;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>   \r\n");
      out.write("    <header>\r\n");
      out.write("            <nav class=\"navbar\">\r\n");
      out.write("                <div class=\"logo\">DocCare</div>\r\n");
      out.write("                <ul class=\"nav-links\">\r\n");
      out.write("                    <li><a href=\"#\" class=\"link active\" >Home</a></li>\r\n");
      out.write("                     <li><a href=\"#\" class=\"link \">Lab Report</a></li>\r\n");
      out.write("                    <li><a href=\"set\" class=\"link \">set availability</a></li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li><a href=\"display\" class=\"link \">availabilities</a></li>\r\n");
      out.write("                    <li><a href=\"AppointmentDisplayServlet\" class=\"link \">Appointments</a></li>\r\n");
      out.write("                    <li><a href=\"PatientAccServlet\" class=\"link \">Profile</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"auth-buttons\">\r\n");
      out.write("                    \r\n");
      out.write("                    <form action=\"logoutServlet\" method=\"get\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn\">Log Out</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write(" ");
 
     String id=request.getParameter("lid");
     String name=request.getParameter("hName");
     String pname=request.getParameter("patientName");
     String test=request.getParameter("testType");
     String details=request.getParameter("testResult");
     String date=request.getParameter("date");
     
      out.write("\r\n");
      out.write("     <section id=\"delete-section\">\r\n");
      out.write("    <div class=\"delete-container\">\r\n");
      out.write("        <h2>Delete Lab Report</h2>\r\n");
      out.write("<form action=\"delete\" method=\"post\">\r\n");
      out.write("            <div class=\"profile-field\">\r\n");
      out.write("                <label for=\"HID\">Lab Id:</label>\r\n");
      out.write("                <input type=\"text\" id=\"id\" name=\"lid\" value=\"");
      out.print(id);
      out.write("\"readonly>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"profile-field\">\r\n");
      out.write("                <label for=\"Hname\">Hospital Name:</label>\r\n");
      out.write("                <input type=\"text\" id=\"hname\" name=\"hname\" value=\"");
      out.print(name);
      out.write("\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"profile-field\">\r\n");
      out.write("                <label for=\"Pname\">Patient Name:</label>\r\n");
      out.write("                <input type=\"text\" id=\"pname\" name=\"pname\" value=\"");
      out.print(pname);
      out.write("\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"profile-field\">\r\n");
      out.write("                <label for=\"test\">Test:</label>\r\n");
      out.write("                <input type=\"text\" id=\"test\" name=\"test\" value=\"");
      out.print(test);
      out.write("\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"profile-field\">\r\n");
      out.write("                <label for=\"details\">Test Result:</label>\r\n");
      out.write("                <input type=\"text\" id=\"details\" name=\"details\" value=\"");
      out.print(details);
      out.write("\"required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"profile-field\">\r\n");
      out.write("                <label for=\"date\">Date:</label>\r\n");
      out.write("                <input type=\"text\" id=\"phone\" name=\"date\"value=\"");
      out.print(date);
      out.write("\"required>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            <button type=\"submit\" class=\"update-btn\" name=\"submit\" value=\"submit\">Delete</button>\r\n");
      out.write("        </form>\r\n");
      out.write("         </div>\r\n");
      out.write("</section>\r\n");
      out.write(" <footer>\r\n");
      out.write("        <div class=\"footer-container\">\r\n");
      out.write("            <p>© 2024 City Hospital | All Rights Reserved</p>\r\n");
      out.write("            <p>Contact Us: (123) 456-7890 | info@cityhospital.com</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
