/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-10-13 04:17:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Login  and Registration Form</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/login.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navigation Bar -->\r\n");
      out.write("    <div class=\"nav\">\r\n");
      out.write("        <div class=\"nav-logo\">\r\n");
      out.write("            <p>DocCare</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-menu\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\" class=\"link \">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"link\">About</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"link\">Doctor</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"link\">Appointment</a></li>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-button\">\r\n");
      out.write("            <button class=\"btn white-btn\" id=\"loginBtn\" onclick=\"login()\">Sign In</button>\r\n");
      out.write("            <button class=\"btn\" id=\"registrationBtn\" onclick=\"register()\">Sign Up</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Wrapper -->\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"form-box\">\r\n");
      out.write("            <!-- Login Form -->\r\n");
      out.write("            <div id=\"login\" class=\"login-container active\">\r\n");
      out.write("                <span>Don't have an account? <a href=\"#\" onclick=\"register()\">Sign In</a></span>\r\n");
      out.write("                <header>Log In</header>\r\n");
      out.write("                <form action=\"PatientLoginServlet\" method=\"post\">\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <i class=\"fas fa-user\"></i>\r\n");
      out.write("                        <input type=\"text\" class=\"input-field\" name=\"patientUsername\" placeholder=\"Username\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <i class=\"fas fa-lock\"></i>\r\n");
      out.write("                        <input type=\"password\" class=\"input-field\" name=\"patientPassword\" placeholder=\"Password\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <i class=\"fas fa-user-tag\"></i>\r\n");
      out.write("                        <select name=\"userType\" class=\"input-field\" required>\r\n");
      out.write("                            <option value=\"\">Select Login Type</option>\r\n");
      out.write("                            \r\n");
      out.write("                            <option value=\"patient\">Patient</option>\r\n");
      out.write("                            <option value=\"docadmin\">Doc Admin</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"submit\" class=\"submit\" name=\"loginPatientSubmit\" id=\"signin\" value=\"Log In\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Register Form -->\r\n");
      out.write("            <div id=\"register\" class=\"register-container\">\r\n");
      out.write("                <span>Have an account? <a href=\"#\" onclick=\"login()\">Login</a></span>\r\n");
      out.write("                <header>Create Account</header>\r\n");
      out.write("                <form action=\"PatientCreateAccServlet\" method=\"post\">\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <i class=\"fas fa-user\"></i>\r\n");
      out.write("                        <input type=\"text\" class=\"input-field\" name=\"fname\"  placeholder=\"First Name\" required >\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <i class=\"fas fa-user\"></i>\r\n");
      out.write("                        <input type=\"text\" class=\"input-field\" name=\"lname\"  placeholder=\"Last Name\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <i class=\"fas fa-user\"></i>\r\n");
      out.write("                        <input type=\"text\" class=\"input-field\" name=\"phone\"  placeholder=\"Phone\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <i class=\"fas fa-user\"></i>\r\n");
      out.write("                        <input type=\"text\" class=\"input-field\" name=\"dob\"  placeholder=\"DOB\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("                        <input type=\"email\" class=\"input-field\" name=\"email\"  placeholder=\"Email\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <i class=\"fas fa-lock\"></i>\r\n");
      out.write("                        <input type=\"password\" class=\"input-field\" name=\"password\"  placeholder=\"Password\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"submit\" class=\"submit\" name=\"submit\" value=\"Register\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/scripts.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
